### ISSUE TITLE
Is it possible to clean up cache folder by source path?

### ISSUE THREAD

**Issue by marynate** [bozaro/octobuild#11]
My ".octobuild\cache" folder is getting bigger and bigger, I wonder if I can clean up part of them by source path? Say I want to keep cache of "e:\unreal_project1" and clean up cache for "e:\unreal_project2".

**Comment by bozaro** [comment]
Current state:

 * No way to cleanup cache for specific project;
 * You can set cache location by OCTOBUILD_CACHE environment variable;
 * Cache size limitited by 16Gb (non-configurable yet);
 * I plannig to make configuration file for octobuild.

**Comment by marynate** [comment]
Thanks bozaro! Good to know that there's 16Gb size limitation. (That's cool since I don't have to worry my HD be full soon )

Btw, I just can't live without octobuild now.

**Comment by marynate** [comment]
Hi bozaro, when cache size reach the 16Gb limit, what will be the behavior? Will octobuild overwrite oldest cache file or simply stop caching until the cache folder been clean up manually?

**Comment by bozaro** [comment]
Octobuild use LRU cache.
On octobuild complete build job, it make all cached files list and keep first 16G resently used files.
So, on build time cache can be little bigger then 16Gb.
Cache usage time gets from OS file modification time. File modification time sets by octobuild on every cache file usage (becase file access time resently not updated by OS).

**Comment by bozaro** [comment]
Cache size and location can be redefined with configuration file in 0.1.10+
