### ISSUE TITLE
Can't use octobuild for compiling file (Unrealengine master/4.13 branch)

### ISSUE THREAD

**Issue by marynate** [bozaro/octobuild#13]
`4>  Can't use octobuild for compiling file, use failback compilation: Error { repr: Custom(Custom { kind: InvalidInput, error: InvalidArguments("Can\'t detect file language by extension: \"@E:\\\\dev\\\\unreal\\\\git\\\\UnrealEngine\\\\Engine\\\\Intermediate\\\\Build\\\\Win64\\\\UnrealHeaderTool\\\\Development\\\\CoreUObject\\\\Module.CoreUObject.2_of_5.cpp.obj.response\"") }) }`

It seems octobuild no longer working in master/4.13 branch. (4.12 branch is fine)

**Comment by marynate** [comment]
`https://github.com/EpicGames/UnrealEngine/blame/master/Engine/Source/Programs/UnrealBuildTool/Windows/VCToolChain.cs#L1336`

Now UBT is using response file which octobuild seems has problem to understand. Revert back the commit makes octobuild happy again.

**Comment by bozaro** [comment]
I will add support for this change in few days.

**Comment by marynate** [comment]
Hi @bozaro , Is there instruction of building octobuild?

**Comment by bozaro** [comment]
Unfortunatelly I don't write octobuild compilation page.

## Ubuntu
On Ubuntu it's really simple:
```bash
# Prepare environment
sudo apt-get install gcc mingw-w64
# Install Rust (see https://rustup.rs for more details)
curl https://sh.rustup.rs -sSf | sh
rustup toolchain install stable
rustup target add x86_64-pc-windows-gnu
# Build
git clone https://github.com/bozaro/octobuild.git
cd octobuild
cargo build --release --target x86_64-pc-windows-gnu
cargo build --release --target x86_64-unknown-linux-gnu
```

Cross compiling for i686-pc-windows-gnu is little more complex: https://github.com/rust-lang/rust/issues/32859

## Windows
For Windows I have not step-by-step instruction. Unfortunatelly I have no fresh Windows host to write them.

I build Windows version on Linux :)

I think, simplest way to compile on Windows with Visual Studio:

- Install Rustup (https://www.rustup.rs/);
- Install Rust toolchain for Visual Studio:
```
rustup default stable-msvc
```
- Build
```
git clone https://github.com/bozaro/octobuild.git
cd octobuild
cargo build --release
```

**Comment by marynate** [comment]
Thanks a lot for the instructions. My PC is down.right now. Will try afiter it's fixed.
