### ISSUE TITLE
UE 4.12.2 fails to compile "Basic Code" C++ project

### ISSUE THREAD

**Issue by slonopotamus** [bozaro/octobuild#14]
Way to reproduce:

1. Install UE 4.12.2 via Epic Games launcher
2. New project -> C++ -> Basic Code, no starter content

Expected: editor opens newly-created project

Actual:

	Running C:/Program Files (x86)/Epic Games/4.12/Engine/Binaries/DotNET/UnrealBuildTool.exe MyProject Development Win64 -project="C:/Users/m.radchenko/Documents/Unreal Projects/MyProject/MyProject.uproject" -editorrecompile -progress -noubtmakefiles -NoHotReloadFromIDE
	@progress push 5%
	Parsing headers for MyProjectEditor
	  Running UnrealHeaderTool "C:\Users\m.radchenko\Documents\Unreal Projects\MyProject\MyProject.uproject" "C:\Users\m.radchenko\Documents\Unreal Projects\MyProject\Intermediate\Build\Win64\MyProjectEditor\Development\MyProjectEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
	Reflection code generated for MyProjectEditor in 2,873731 seconds
	@progress pop
	Distributing 7 actions to XGE
	xgConsole (0.1.12-x86_64-windows, rev: 7d13c4133, rustc: 1.7.0):
	  xgConsole
	  ../../Engine/Intermediate/Build/XGETasks.xml
	  /Rebuild
	  /NoWait
	  /StopOnErrors
	  /NoLogo
	  /ShowTime
	  /UseIdeMonitor
	#0 1/7: @actionModuleVersionResource.rc.inl
	#2 2/7: @actionPCLaunch.rc
	Can't use octobuild for compiling file, use failback compilation: Error { repr: Os { code: 21, message: "\u{423}\u{441}\u{442}\u{440}\u{43e}\u{439}\u{441}\u{442}\u{432}\u{43e} \u{43d}\u{435} \u{433}\u{43e}\u{442}\u{43e}\u{432}\u{43e}." } }
	#1 3/7: PCH.MyProject.h.cpp
	PCH.MyProject.h.cpp
	Can't use octobuild for compiling file, use failback compilation: Error { repr: Os { code: 21, message: "\u{423}\u{441}\u{442}\u{440}\u{43e}\u{439}\u{441}\u{442}\u{432}\u{43e} \u{43d}\u{435} \u{433}\u{43e}\u{442}\u{43e}\u{432}\u{43e}." } }
	Can't use octobuild for compiling file, use failback compilation: Error { repr: Os { code: 21, message: "\u{423}\u{441}\u{442}\u{440}\u{43e}\u{439}\u{441}\u{442}\u{432}\u{43e} \u{43d}\u{435} \u{433}\u{43e}\u{442}\u{43e}\u{432}\u{43e}." } }
	Can't use octobuild for compiling file, use failback compilation: Error { repr: Os { code: 21, message: "\u{423}\u{441}\u{442}\u{440}\u{43e}\u{439}\u{441}\u{442}\u{432}\u{43e} \u{43d}\u{435} \u{433}\u{43e}\u{442}\u{43e}\u{432}\u{43e}." } }
	#4 4/7: MyProjectGameMode.cpp
	MyProjectGameMode.cpp
	#3 5/7: MyProject.cpp
	MyProject.cpp
	#5 6/7: MyProject.generated.cpp
	MyProject.generated.cpp
	#0 7/7: @actionUE4Editor-MyProject.dll
	   Creating library C:\Users\m.radchenko\Documents\Unreal Projects\MyProject\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-MyProject.lib and object C:\Users\m.radchenko\Documents\Unreal Projects\MyProject\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-MyProject.exp

	MyProject.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class TBaseDelegate<class FFixedUObjectArray *> & __cdecl FCoreDelegates::GetObjectArrayForDebugVisualizersDelegate(void)" (__imp_?GetObjectArrayForDebugVisualizersDelegate@FCoreDelegates@@SAAEAV?$TBaseDelegate@PEAVFFixedUObjectArray@@$$$V@@XZ) referenced in function "void __cdecl `dynamic initializer for 'GObjectArrayForDebugVisualizers''(void)" (??__EGObjectArrayForDebugVisualizers@@YAXXZ)
	MyProjectGameMode.cpp.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl AGameMode::SetPause(class APlayerController *,class TBaseDelegate<bool>)" (?SetPause@AGameMode@@UEAA_NPEAVAPlayerController@@V?$TBaseDelegate@_N$$$V@@@Z)
	MyProject.generated.cpp.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl AGameMode::SetPause(class APlayerController *,class TBaseDelegate<bool>)" (?SetPause@AGameMode@@UEAA_NPEAVAPlayerController@@V?$TBaseDelegate@_N$$$V@@@Z)
	C:\Users\m.radchenko\Documents\Unreal Projects\MyProject\Binaries\Win64\UE4Editor-MyProject.dll : fatal error LNK1120: 2 unresolved externals
	Cache statistic: hit 0 of 0 (0 %), read 0, write 0, total 0

	ERROR: UBT ERROR: Failed to produce item: C:\Users\m.radchenko\Documents\Unreal Projects\MyProject\Binaries\Win64\UE4Editor-MyProject.dll
	XGE execution time: 75,32 seconds

**Comment by bozaro** [comment]
Octobuild 0.1.12 can't compile UE 4.12. Try latest version please.

**Comment by slonopotamus** [comment]
Update: after installing Octobuild 0.1.13 and VS 2015 Community I now get this:

	xgConsole (0.1.13-x86_64-windows, rev: 870377209, rustc: 1.9.0):
	  xgConsole
	  ../../Engine/Intermediate/Build/XGETasks.xml
	  /Rebuild
	  /NoWait
	  /StopOnErrors
	  /NoLogo
	  /ShowTime
	  /UseIdeMonitor
	#1 1/7: @actionPCLaunch.rc
	#2 2/7: @actionModuleVersionResource.rc.inl
	Can't use octobuild for compiling file, use failback compilation: Error { repr: Os { code: 21, message: "\u{423}\u{441}\u{442}\u{440}\u{43e}\u{439}\u{441}\u{442}\u{432}\u{43e} \u{43d}\u{435} \u{433}\u{43e}\u{442}\u{43e}\u{432}\u{43e}." } }
	#0 3/7: PCH.MyProject.h.cpp
	PCH.MyProject.h.cpp
	Can't use octobuild for compiling file, use failback compilation: Error { repr: Os { code: 21, message: "\u{423}\u{441}\u{442}\u{440}\u{43e}\u{439}\u{441}\u{442}\u{432}\u{43e} \u{43d}\u{435} \u{433}\u{43e}\u{442}\u{43e}\u{432}\u{43e}." } }
	Can't use octobuild for compiling file, use failback compilation: Error { repr: Os { code: 21, message: "\u{423}\u{441}\u{442}\u{440}\u{43e}\u{439}\u{441}\u{442}\u{432}\u{43e} \u{43d}\u{435} \u{433}\u{43e}\u{442}\u{43e}\u{432}\u{43e}." } }
	Can't use octobuild for compiling file, use failback compilation: Error { repr: Os { code: 21, message: "\u{423}\u{441}\u{442}\u{440}\u{43e}\u{439}\u{441}\u{442}\u{432}\u{43e} \u{43d}\u{435} \u{433}\u{43e}\u{442}\u{43e}\u{432}\u{43e}." } }
	#4 4/7: MyProject.cpp
	MyProject.cpp
	#5 5/7: MyProjectGameMode.cpp
	MyProjectGameMode.cpp
	#3 6/7: MyProject.generated.cpp
	MyProject.generated.cpp
	#1 7/7: @actionUE4Editor-MyProject.dll
	   Creating library C:\Users\m.radchenko\Documents\Unreal Projects\MyProject\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-MyProject.lib and object C:\Users\m.radchenko\Documents\Unreal Projects\MyProject\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-MyProject.exp
	Cache statistic: hit 0 of 0 (0 %), read 0, write 0, total 0


	XGE execution time: 48,45 seconds

**Comment by bozaro** [comment]
This error caused by using Visual Studio 2013 instead of Visual Studio 2015.
