### ISSUE TITLE
Incompatible with VS2017

### ISSUE THREAD

**Issue by S-ed** [bozaro/octobuild#24]
Probably was not intended to be used with it. But still.
Compiler using fallback for every operation on VS2017 (maybe it's just the Incredibuild's fault).

**Comment by bozaro** [comment]
How I can reproduce this issue?

**Comment by S-ed** [comment]
Does VS2017 working for You? (i.e. compiling ue4)
All I did is enabled Octobuild for ue4 source compilation (ue4 still has some path issues if You have no VS2015 installed).

**Comment by slonopotamus** [comment]
We need the logic to find where VS 2017 is installed. See rust-lang/rust#42225.

**Comment by slonopotamus** [comment]
octobuild 0.2.3 works with VS2019 (at least for UE-5.0.3). There are no plans to add support for older UE versions.
