### ISSUE TITLE
Can't use octobuild to compile UE4 master branch

### ISSUE THREAD

**Issue by marynate** [bozaro/octobuild#25]
It seems octobuild has problem to build UE4 master branch sicne the "include header only what you need" change.

Error message:

`Can't use octobuild for compiling file, use failback compilation: Error { repr: Custom(Custom { kind: InvalidInput, error: InvalidArguments("Found too many source files: [\"E:\\\\dev\\\\unreal\\\\git\\\\UnrealEngine\\\\Engine\\\\Source\\r\\n/I\", \"E:\\\\dev\\\\unreal\\\\git\\\\UnrealEngine\\\\Engine\\\\Source\\\\Runtime\\\\GameplayTags\\\\Private\\r\\n/I\", \"E:\\\\dev\\\\unreal\\\\git\\\\UnrealEngine\\\\Engine\\\\Source\\\\Runtime\\\\GameplayTags\\\\Classes\\r\\n/I\", \"E:\\\\dev\\\\unreal\\\\git\\\\UnrealEngine\\\\Engine\\\\Source\\\\Runtime\\\\GameplayTags\\\\Public\\r\\n/I\", \"E:\\\\dev\\\\unreal\\\\git\\\\UnrealEngine\\\\Engine\\\\Intermediate\\\\Build..."`

**Comment by slonopotamus** [comment]
@marynate: that error ("too many source files") doesn't exist since commit 0140fb167572ef1dc73acafb6c14428dc18fb18f. Try updating to latest octobuild (0.1.14).

**Comment by slonopotamus** [comment]
Closing, got no feedback since 2017.
