### ISSUE TITLE
[UE-4.22+] Can't use octobuild for task "XXX" can't find toolchain for cl-filter.exe

### ISSUE THREAD

**Issue by S-ed** [bozaro/octobuild#40]
Greetings.
I've recently tried to compile master with the octobuild and every binary gives me an error like this:

> 11>Can't use octobuild for task LightPropagationVolumeBlendableFactory.gen.cpp: can't find toolchain for: Z:\Dev\UE4\Master\Engine\Build\Windows\cl-filter\cl-filter.exe
> 11>Can't use octobuild for task UE4Editor-MagicLeapAR.dll: can't find toolchain for: C:\Dev\Visual Studio 2017\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe
> 11>Can't use octobuild for task UE4Editor-GeometryCollectionSimulationCore.lib: can't find toolchain for: C:\Dev\Visual Studio 2017\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\lib.exe

I wish I could understand how to solve the issue, but my understanding of how IncrediBuild works is close to zero.

**Comment by slonopotamus** [comment]
The problem is: starting with UE-4.22 there is a [cl-filter.exe wrapper](https://github.com/EpicGames/UnrealEngine/commit/0c9707d678d3237ea5656408d3fb389cbaf1c2a5#diff-1f6155d6d6adcf8c92f31f26eab5e493) that confuses octobuild because octobuild no longer knows what toolchain (vs/clang) is used.

**Comment by jeevcat** [comment]
Any progress on this issue? Can we just tell octobuild which toolchain is being used via configuration?

**Comment by slonopotamus** [comment]
UE5 no longer uses cl-filter, so octobuild can be used again. There are no plans to add cl-filter.exe support to octobuild for older UE versions.
