### ISSUE TITLE
Resurrect releases pipeline

### ISSUE THREAD

**Issue by slonopotamus** [bozaro/octobuild#47]
CI -> Bintray + GitHub-Releases + (optionally) Chocolatey

**Comment by slonopotamus** [comment]
1. Create https://bintray.com/bozaro/octobuild Bintray repository (type=Debian)
2. Enable GPG signing on https://bintray.com/bozaro/octobuild/edit?tab=general
3. In Travis settings of https://travis-ci.org/bozaro/octobuild
3.1. `GITHUB_TOKEN` = github api token (for github releases)
3.2. `BINTRAY_USER` = `bozaro`
3.3. `BINTRAY_TOKEN` = bintray token from https://bintray.com/profile/edit

**Comment by budgidiere** [comment]
how do I get latest msi?

**Comment by slonopotamus** [comment]
Latest msi is [0.1.14](https://github.com/bozaro/octobuild/releases/tag/0.1.14). Current octobuild code doesn't work with modern UE4 versions, so there's no point making new releases.

**Comment by slonopotamus** [comment]
Instead of Bintray (it is dead), we should use https://cloudsmith.io instead.

**Comment by slonopotamus** [comment]
So. We have MSI+Deb working and both are attached to GitHub releases. Publishing to other places (WinGet/Chocolatey/CloudSmith) will be done in separate issues.
