### ISSUE TITLE
cargo build fail

### ISSUE THREAD

**Issue by mathslimin** [bozaro/octobuild#65]
error[E0658]: `cfg(doctest)` is experimental and subject to change
 --> C:\Users\l00533159\.cargo\registry\src\mirrors\xml-rs-0.8.3\src/lib.rs:9:7
  |
9 | #[cfg(doctest)]
  |       ^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/62210

**Comment by slonopotamus** [comment]
I don't reproduce this error. Please, make sure that you use current `stable` Rust.
